### ISSUE TITLE
"try again later" message displayes when bot starts conversation

### ISSUE THREAD

**Issue by jwheat** [JiteshGaikwad/Chatbot-Widget#1]
The second message from the bot is always the 'try again later' message if it is configured to start the conversation.

To reproduce this -

**script.js**
- set an action_name to an utterance (line 7)
- uncomment line 11 `action_trigger()`
- open / refresh index.html

**What happens**
When the bot loads, the initial greeting is displayed as expected.
I type a message such as `Hi`
The bot responds with _**I am facing some issues, please try again later!!!**_
If you continue the conversation, everything is fine.

I haven't worked out why this happens yet.

**Comment by Prskriti** [comment]
I am also facing same issue

**Comment by JiteshGaikwad** [comment]
Hey @Prskriti  can you show me the action which you have configured for action trigger.

**Comment by iamabhishekchakraborty** [comment]
@JiteshGaikwad this works fine when used and tested in localhost, no issues at all. But I am getting the same message when I tried deploying the code in GCP. Any idea(s) where should the change(s) be done?

**Comment by JiteshGaikwad** [comment]
@iamabhishekchakraborty  what's the error you are getting?

**Comment by iamabhishekchakraborty** [comment]
When looked into console I get this - "Error from bot end:  error"
From bot the reply is - "I am facing some issues, please try again later!!!"

**Comment by JiteshGaikwad** [comment]
@iamabhishekchakraborty  sorry but I Haven't deployed the bot to the cloud yet so I don't have any idea about that😅

**Comment by iamabhishekchakraborty** [comment]
No problem. Any idea(s) or link(s) you could point me to, that would be really helpful.

**Comment by JiteshGaikwad** [comment]
Sorry for that but I don't have any idea about that but you can connect with me on LinkedIn and we can remotely connect and I can try to have a look over the issues

**Comment by JiteshGaikwad** [comment]
Hey @jwheat , @Prskriti , I have fixed the issue, it was due to `EmbeddingPolicy`  which was not able to predict the next action after we have triggered the custom actions, so I have chnage the policy in the Restaurant bot to the default configuration and it worked. you can test it and let me know if still you face the same issue even after changing the policy. just have a look over this and let me know:
> https://github.com/JiteshGaikwad/Restaurant-Search-Bot/blob/8d07f2d9230f3a012af59203f958c4bd267f5cd8/config.yml#L12

Regards,
Jitesh

**Comment by Prskriti** [comment]
Hi @JiteshGaikwad I checked and it's working now

**Comment by JiteshGaikwad** [comment]
Closing the issue since it has been fixed.
