### ISSUE TITLE
Sign in page popup for login.

### ISSUE THREAD

**Issue by ashrafulyarali** [JiteshGaikwad/Chatbot-Widget#15]
How to integrate login page to UI.

**Comment by shreyashgupta68** [comment]
Don't know.

**Comment by JiteshGaikwad** [comment]
this Chatbot UI doesn't have support for login form

**Comment by ashrafulyarali** [comment]
see i try something like that with after click current one
![image](https://user-images.githubusercontent.com/22020219/205231105-4acea24e-08c3-407d-b7e0-62a1c5c114ce.png)

after click
![image](https://user-images.githubusercontent.com/22020219/205231218-bfcd14b0-a079-4168-a73d-d7481c1f382b.png)

**Comment by ashrafulyarali** [comment]
![image](https://user-images.githubusercontent.com/22020219/205231339-63e431aa-74f6-48bd-901a-1593f9060318.png)

**Comment by ashrafulyarali** [comment]
see this look like this
![image](https://user-images.githubusercontent.com/22020219/205231401-df0f87ff-0616-4513-8e9c-6f839ce54c43.png)

**Comment by JiteshGaikwad** [comment]
this widget is fully customizable & I see you have designed the login form, so what's the issue?

**Comment by ashrafulyarali** [comment]
issue is that i want validations from custom action take those parameter(login_id,pass) from user and pass to custom action.

**Comment by JiteshGaikwad** [comment]
since you have added the login form I don't know the design of it, you need to handle those things, I can't help you with this but I can suggest that you can pass the parameters to rasa, you can add rules for the same in which you can can call the custom actions, calling custom actions directly will affect the conversation flow

**Comment by JiteshGaikwad** [comment]
I am closing this issue since this is not the feature of my widget, thanks

**Comment by ashrafulyarali** [comment]
ok thanks
