### ISSUE TITLE
Embed bot without button

### ISSUE THREAD

**Issue by jcechavarri** [JiteshGaikwad/Chatbot-Widget#16]
Hey @JiteshGaikwad!

Is it possible to embed just the bot in the page instead of the button? I was thinking something like the `embedded` prop of [botfront's widget](https://github.com/botfront/rasa-webchat#parameters).

Thank you 😄

**Comment by JiteshGaikwad** [comment]
Hey @jcechavarri I have added this feature in [Widget.20](https://github.com/JiteshGaikwad/Chatbot-Widget/tree/Widget2.0), you can check the `demo.html` file for the above feature, although it's still w.i.p but basic messaging works.

**Comment by JiteshGaikwad** [comment]
@jcechavarri since it's still in development, any feedback is welcome 😄

**Comment by jcechavarri** [comment]
@JiteshGaikwad thank you for the quick reply 😁 

However, I do not find the prop in `demo.html` as you explain. Maybe I explained myself wrong. I would like to have a prop `embedded`, which can be `true` or `false`:

Example:

#### Embedded true
`<Widget embedded={{ true }} />`

<img width="500px" src="https://user-images.githubusercontent.com/42159312/202199219-323d5569-567d-4c64-aeda-a6269809fe04.png" />

Note that the launcher button does not exist with embedded = true.


#### Embedded false
`<Widget embedded={{ false }} />`

<img width="500px" src="https://user-images.githubusercontent.com/42159312/202198867-10b95e15-2417-43a0-9559-b759fa09b81c.png" />


If the option already exists, please tell me where to find it 🙏🏼

**Comment by JiteshGaikwad** [comment]
@jcechavarri I have added the `embedded` prop as you suggested please check the `demo.html` file for the latest changes.
Thanks for suggesting the feature. 😄 🙏

**Comment by jcechavarri** [comment]
Will check it out, thank you again!! 🚀

**Comment by jcechavarri** [comment]
Closing this issue, as it is resolved ⭐
