### ISSUE TITLE
Sending hyperlinks from custom action.

### ISSUE THREAD

**Issue by jaseel97** [JiteshGaikwad/Chatbot-Widget#16]
The documentation doesn't mention anything about sending links as reply. Right now, urls sent as part of a reply are behaving like text and not links. How do I send links as a message?

**Comment by JiteshGaikwad** [comment]
You can send it using <a> tag

**Comment by jaseel97** [comment]
Oh, okay. I'm a noob when it comes to web dev. It totally didn't occur to me. Thanks mate.

**Comment by saraswathykrk** [comment]
> You can send it using tag

Can you please show me an example?

**Comment by jaseel97** [comment]
@saraswathykrk  Its like this:
`link = 'www.example.com'
text = 'Click Here'
msg = '<a href="{}"> {} </a>'.format(link,text)
dispatcher.utter_message(msg)`

**Comment by saraswathykrk** [comment]
Hi jaseel97,

Thank you so much! What is the syntax for keeping hyperlinks in the domain.yml file? I am trying with markdown format but in vain!

**Comment by saraswathykrk** [comment]
Also, would you have any idea how to code the same in telegram as in Chatbot-Widget, because the above code worked perfectly in Chatbot-Widget but shows with the tags in telegram. I was earlier using the markdown format in telegram which seemed to work, but is not working in Chatbot for me.

**Comment by jaseel97** [comment]
> Hi jaseel97,
> 
> Thank you so much! What is the syntax for keeping hyperlinks in the domain.yml file? I am trying with markdown format but in vain!

Markdown for links only work if you are using rasa x. In fact, how the text in the domain.yml or text sent from custom actions are processed depend on the front-end. I think html tags in the domain file should work with Chatbot-Widget.

**Comment by saraswathykrk** [comment]
ok makes sense. Thanks a lot!

**Comment by saraswathykrk** [comment]
Also, would you be aware if we can give different formats for different channels in the domain file. I read somewhere in the rasa forum I think, that separating it out in the actions file is not a good practice.

**Comment by jaseel97** [comment]
> Also, would you have any idea how to code the same in telegram as in Chatbot-Widget, because the above code worked perfectly in Chatbot-Widget but shows with the tags in telegram. I was earlier using the markdown format in telegram which seemed to work, but is not working in Chatbot for me.

If you are using the telegram API, it has a parameter parse_mode which can be set to html like so:
`https://api.telegram.org/bot......&parse_mode=html&`...

**Comment by saraswathykrk** [comment]
> `https://api.telegram.org/bot......&parse_mode=html&`...

Where should I be using this?

**Comment by JiteshGaikwad** [comment]
Hey @saraswathykrk check this docs for sending channel specific response:

https://rasa.com/docs/rasa/core/domains/#channel-specific-responses

**Comment by jaseel97** [comment]
> > `https://api.telegram.org/bot......&parse_mode=html&`...
> 
> Where should I be using this?

Are you not using the telegram API? I don't know how the telegram channel of rasa works. But if you are using the api endpoints directly, then you can use the parse_mode parameter.

**Comment by saraswathykrk** [comment]
I was using the custom payload, with parse_mode: markdown in domain file and that was working.
Apart from that had set the webhooks in the credentials. Hadnt used any API calls as such.
