### ISSUE TITLE
Show how to connect to Rasa on remote server

### ISSUE THREAD

**Issue by ltfschoen** [JiteshGaikwad/Chatbot-Widget#17]
If you're running the Rasa server on a remote server like an EC2 instance, it is necessary to modify https://github.com/JiteshGaikwad/Chatbot-Widget/blob/main/static/js/constants.js#L2 an replace `localhost` with the public IP address of the server, only then will it connect. Suggest updating the instructions to mention that

**Comment by JiteshGaikwad** [comment]
@ltfschoen instructions updated, thanks for the suggestion :)
