### ISSUE TITLE
Deploy problem

### ISSUE THREAD

**Issue by jcechavarri** [JiteshGaikwad/Chatbot-Widget#18]
Hey @JiteshGaikwad!

I'm having some dumb problem with the Widget 2.0. Running the app locally with `npm start` works fine, but when I try to deploy it, it shows some `BundleAnalyzer` stuff. I tried removing the plugin from `webpack.config.js` and the deploy shows just a black screen (does not load the bot).

Could you give me a hint on how to deploy the bot or fix the config please? 

Thank you

**Comment by JiteshGaikwad** [comment]
can you share the screenshots  with steps that you have followed

**Comment by jcechavarri** [comment]
Of course! 

### Step 1: Clone repo & checkout Widget2.0 branch

![image](https://user-images.githubusercontent.com/42159312/203099666-0429c80f-b10f-437d-9396-067b6ac046a1.png)


### Step 2: `npm install`
![image](https://user-images.githubusercontent.com/42159312/203100068-92471757-b6e3-4a3f-af5c-67588ada94e2.png)

### Step 3: `npm start`
![image](https://user-images.githubusercontent.com/42159312/203100328-85c1c690-6735-43d1-865f-bd86859f5521.png)

`http://localhost:3000`
![image](https://user-images.githubusercontent.com/42159312/203100421-fad543a5-bcd1-48b0-9dd5-b636bbae58c1.png)

### Step 4: `npm run build`
![image](https://user-images.githubusercontent.com/42159312/203100959-48ca25b4-1417-4d83-b9d0-5d8a8f4bb80e.png)

Automatically opens up `http://localhost:8888`
![image](https://user-images.githubusercontent.com/42159312/203101175-cf013dd8-8c87-4818-932a-d0fa119ed41b.png)

### Step 5: Test build with `serve -s dist`
![image](https://user-images.githubusercontent.com/42159312/203101873-a4eee14b-73f0-4ea2-ab62-757cf567947e.png)

### Step 6: Check webpack config & change plugin
Changed line 54: replace `BundleAnalyzerPlugin` with `HtmlWebPackPlugin`
![image](https://user-images.githubusercontent.com/42159312/203102190-de13c03d-405c-4d5a-bcd7-2c2e78a2caa7.png)

### Step 7: Run build again & test build
`npm run build`
![image](https://user-images.githubusercontent.com/42159312/203102672-38272b2c-19e1-40ad-8954-b8c2c234b772.png)

`serve -s dist`
![image](https://user-images.githubusercontent.com/42159312/203102816-259c09a3-9510-490e-afa8-8f2df06fd448.png)

`http://localhost:3000`
![image](https://user-images.githubusercontent.com/42159312/203103050-74b4c361-98d4-4fde-ba48-956b76443fca.png)

**Comment by JiteshGaikwad** [comment]
@jcechavarri I have added the fix, you were getting the issue since you didn't load the `ChatbotWidget` module, I have added the html template in `public/` folder named as `webpack_template.html` you can also check the webpack config for the same, and the above solution didn't worked for your because I created custom config of webpack for the app.

**Comment by mesut-shuja** [comment]
@JiteshGaikwad hi, I am using your chatbot for rasa. Is there a feature for markdown with this widget ? I was trying [For More](http://.....) but this isnt working. Also how can integrate this widget to my website ? Where can I find the script tag ?
Thanks
