### ISSUE TITLE
adding PDF

### ISSUE THREAD

**Issue by blueberrykary** [JiteshGaikwad/Chatbot-Widget#18]
How do you add pdf file onto the domain.yml? Or in the actions.py?

**Comment by JiteshGaikwad** [comment]
The pdf file is store somewhere in the cloud and from there I am fetching it as a url and rendering it in the browser, I am using url in the domain.yml or actions.py

**Comment by LeeSangHyeup** [comment]
here is example code in domain.yml

`responses:
  utter_greet:
    - text: "Hey! How are you?"
      custom:
        payload: pdf_attachment
        title: "blabla"
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"`

**Comment by LeeSangHyeup** [comment]
here is example code in domain.yml

![image](https://user-images.githubusercontent.com/65228113/89753525-9fcb8c00-db13-11ea-83a3-a85e343d38a7.png)
