### ISSUE TITLE
How to access the location.js?

### ISSUE THREAD

**Issue by shreyashgupta68** [JiteshGaikwad/Chatbot-Widget#19]

**Comment by JiteshGaikwad** [comment]
you need to pass `custom` payload with value as `location` in it, example:
```
dispatcher.utter_message(text="Please allow me access to your location", json_message={
"payload":"location"
}) 
```
https://github.com/JiteshGaikwad/Chatbot-Widget/blob/8afb80bfdf4da4bc3f1d3a320d2943c258ec3eb6/static/js/components/chat.js#L154

**Comment by shreyashgupta68** [comment]
> you need to pass `custom` payload with value as `location` in it, example:
> 
> ```
> dispatcher.utter_message(text="Please allow me access to your location", json_message={
> "payload":"location"
> }) 
> ```
> 
> https://github.com/JiteshGaikwad/Chatbot-Widget/blob/8afb80bfdf4da4bc3f1d3a320d2943c258ec3eb6/static/js/components/chat.js#L154

@JiteshGaikwad sir, will I have to pass this message in custom action and in rule have to map the inform intent with that action (that I have made)

**Comment by JiteshGaikwad** [comment]
yes

**Comment by shreyashgupta68** [comment]
Thanks @JiteshGaikwad sir.

**Comment by JiteshGaikwad** [comment]
closing this issue as it's been resolved

**Comment by shreyashgupta68** [comment]
![image](https://user-images.githubusercontent.com/77537631/205245894-2d4a069e-f1cf-4fd8-9394-598a545719e7.png)

**Comment by shreyashgupta68** [comment]
@JiteshGaikwad sir, it's showing me in loop, after allowing it from the browser. It asks for the user permission again. How to stop the same?

**Comment by JiteshGaikwad** [comment]
can you share  the browser console logs

**Comment by shreyashgupta68** [comment]
![image](https://user-images.githubusercontent.com/77537631/205249177-a004258a-ebd1-4f5d-aa41-e3697cca6691.png)

**Comment by shreyashgupta68** [comment]
![image](https://user-images.githubusercontent.com/77537631/205249294-0ba62bce-72fa-46b1-a7eb-81a2c8b3be89.png)

**Comment by JiteshGaikwad** [comment]
as you can see once you allow the permission for location, it calls `inform` intent and pass the geo location details, you need to handle it accordingly from rasa end else it will keeps prompting for the same location prompt, you need to update the intent name that handles the location params

https://github.com/JiteshGaikwad/Chatbot-Widget/blob/8afb80bfdf4da4bc3f1d3a320d2943c258ec3eb6/static/js/components/location.js#L7

**Comment by shreyashgupta68** [comment]
But in my case @JiteshGaikwad sir, I have used the same **inform ** as my intent name?

**Comment by shreyashgupta68** [comment]
@JiteshGaikwad sir, could you please explain me last line. **You need to update the intent name that handles the location params**
As per my understanding, in location.js *there is an intent inform) which storing the lang and lat of the user location. And In rasa I have made a new intent namely **inform** and passed it to the custom action class and in rules.yml I have mapped the intent ** inform** with the custom action **name**. Should I do something else in this?

**Comment by JiteshGaikwad** [comment]
check your rules or stories are working properly, you can use interactive learning to check ur stories/rules are following the path properly as from the above logs, I don't see error in the chat ui but bot predictions are not following the flow, to ensure flow is working fine test it in interactive mode

**Comment by shreyashgupta68** [comment]
Ok @JiteshGaikwad sir, thanks for your
Reply.
