### ISSUE TITLE
I was unable to link the  ui which is showing error 

### ISSUE THREAD

**Issue by sheggamharshith** [JiteshGaikwad/Chatbot-Widget#19]
I had an error while deployment the ui

I Guedes I have to set the path to the folder where I place so kindly help me with that

**Comment by sheggamharshith** [comment]
how to deploy with existing chatbot I had tried but it is saying models not deployed

**Comment by jwheat** [comment]
It shouldn’t matter where the chatbot widget lives, or what server it is deployed to.  The chatbot widget interacts with the Rasa server via an api, so as long as you’ve deployed the bot properly and changed the url in the widget code, it should work.  

Have you tried getting it to work locally on your machine first?

**Comment by sheggamharshith** [comment]
sir do you how to change the rasa into docker i have resloved the issue but it runs with the webhook right i want it on docker and run on my local host to deploy it on gcs do you have any suggestion or vidoes to how to do it
