### ISSUE TITLE
Chabot-widget not working 

### ISSUE THREAD

**Issue by Prskriti** [JiteshGaikwad/Chatbot-Widget#2]
Getting error on rasa server side 
![Screen Shot 2019-12-24 at 1 45 44 PM](https://user-images.githubusercontent.com/26160349/71401793-e9cd3380-2650-11ea-9eaf-d784854bbf0a.png)

**Comment by jwheat** [comment]
Hi @Prskriti,
This chatbot widget is setup to use the rest API, not socket.io so you need to comment out the `socket.io` section in `credentials.yml` that looks something like this:

```
#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>
```

Give that a try

**Comment by Prskriti** [comment]
Getting Failed to load resource: the server responded with a status of 404 (Not Found) on browser 
![Screen Shot 2019-12-24 at 6 54 40 PM](https://user-images.githubusercontent.com/26160349/71414257-0f236700-267c-11ea-9265-563901a03fee.png)

**Comment by Prskriti** [comment]
Hi @jwheat  
I have already commented socket.io section then also I am facing same issue.
![Screen Shot 2019-12-26 at 1 28 46 PM](https://user-images.githubusercontent.com/26160349/71464812-bfaa7b80-27e0-11ea-90b9-9991e0caf31f.png)

**Comment by Prskriti** [comment]
Getting connection refused error on browser side.

![Screen Shot 2019-12-26 at 1 59 27 PM](https://user-images.githubusercontent.com/26160349/71466300-2c277980-27e5-11ea-92e5-9a1cc41e1fde.png)

**Comment by JiteshGaikwad** [comment]
Hey @Prskriti, are you using the chatbot widget that I have designed or something else because in my widget I don't any url configured that calls socket.io.🙂

**Comment by JiteshGaikwad** [comment]
> Getting connection refused error on browser side.
> 
> ![Screen Shot 2019-12-26 at 1 59 27 PM](https://user-images.githubusercontent.com/26160349/71466300-2c277980-27e5-11ea-92e5-9a1cc41e1fde.png)

To resolve the issue related to webchat integration, check this video: 

https://youtu.be/J1n3Y8SVxVM

**Comment by Prskriti** [comment]
Now I am getting "I am facing some issues, please try again later!!!" as a response each time when asked anything.This is what I am getting on browser side.
![Screen Shot 2019-12-27 at 4 02 56 PM](https://user-images.githubusercontent.com/26160349/71513322-d1af1b80-28bf-11ea-96e6-7734a1e268a2.png)

**Comment by JiteshGaikwad** [comment]
hey @Prskriti, while you are running the rasa server make sure you run using the below command:
> rasa run -m models --enable-api --cors "*" --debug
you are facing the above issue due to **cors**.

**Comment by Prskriti** [comment]
thanks for ur help my bot is working the way as expected. :)

**Comment by JiteshGaikwad** [comment]
Closing the issue since it has been fixed ;)

**Comment by JiteshGaikwad** [comment]
Closing the issue since it has been fixed ;)
