### ISSUE TITLE
After accessing the user location. It's asking for the user location again and again it's not stopping. Please find the below screenshot for your reference if anyone could help me in it will be beneficial for me.

### ISSUE THREAD

**Issue by shreyashgupta68** [JiteshGaikwad/Chatbot-Widget#20]
sir, it's showing me in loop, after allowing it from the browser. It asks for the user permission again. How to stop the same?
![image](https://user-images.githubusercontent.com/77537631/205246243-0066a0db-606a-4789-9bfe-ec74eaebef1a.png)

**Comment by shreyashgupta68** [comment]
action.py code for the same

class ActionSearchHospitals(Action):
    def name(self) -> Text:
        return "action_search_hospitals"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        dispatcher.utter_message(text="Please allow me access to your location", json_message={
            "payload": "location"
        })
        print()
        print("====Inside ActionSearchHospitals====")
        print()
        location = tracker.get_slot("location")
        lat = tracker.get_slot("latitude")
        print("Latitude_slot", lat)
        lon = tracker.get_slot("longitude")
        print("Longitude_slot", lon)
        latEntity = next(tracker.get_latest_entity_values("latitude"), None)
        print(latEntity)
        lonEntity = next(tracker.get_latest_entity_values("longitude"), None)
        print(lonEntity)
        user_locationEntity = next(tracker.get_latest_entity_values("user_location"), None)
        print(user_locationEntity)
        ## if we latitude & longitude entities are found, set it to slot
        if latEntity and lonEntity:
            lat = latEntity
            lon = lonEntity
        if user_locationEntity or (latEntity and lonEntity):
            ## check if we already have the user location coordinates stoed in slots
            if lat == None and lon == None:
                dispatcher.utter_message("Sure, please allow me to access your location 🧐")
                dispatcher.utter_custom_json({"payload": "location"})
        return [UserUtteranceReverted()]

**Comment by shreyashgupta68** [comment]
![image](https://user-images.githubusercontent.com/77537631/205246747-b41ae6e3-dffa-4667-8ee2-6fac63e36bb3.png)
rule.yml

**Comment by shreyashgupta68** [comment]
![image](https://user-images.githubusercontent.com/77537631/205246900-dba41493-cdec-441c-959b-d4bc40cc97b4.png)
training data for inform intent.

**Comment by bawa-v** [comment]
do you get an error in slot validation or in another custom action? you can check this in the console

**Comment by shreyashgupta68** [comment]
@bawa-v  thanks for your comment, but I am able to solve it.

**Comment by bawa-v** [comment]
@shreyashgupta68 okay great! :)
