### ISSUE TITLE
Link is not showing. 

### ISSUE THREAD

**Issue by shreyashgupta68** [JiteshGaikwad/Chatbot-Widget#21]
![image](https://user-images.githubusercontent.com/77537631/208870604-5995f835-ba46-41ec-81c9-729174551d18.png)
Hey everyone,
I tried to pass a link but it's not coming as a link in chatbot need your help in this.

Please find the code for the screenshot.
![image](https://user-images.githubusercontent.com/77537631/208870797-85baf762-c3fc-4e7a-b70e-012bba5631b3.png)
in **link variable** I have the link.

**Comment by JiteshGaikwad** [comment]
please follow the markdown format for sending the link:
```
here is the [link](https://google.com) message
```

**Comment by shreyashgupta68** [comment]
@JiteshGaikwad let me try sir

**Comment by shreyashgupta68** [comment]
@JiteshGaikwad , sir could you please provide any example as it's not working in my case.

**Comment by shreyashgupta68** [comment]
@JiteshGaikwad thanks for your response, sir, it is working fine in domain.yml (cause in this I am using static link) but not for actions.py and in (action.py I am taking the link dynamically from the database)I want to print that link from actions not from the domain. please help me in this.

**Comment by shreyashgupta68** [comment]
Hi everyone I have solved this isse by doing some changes in UI. hence closing the issue.
