### ISSUE TITLE
Request for Guidance on Reducing Response Time in Frontend

### ISSUE THREAD

**Issue by WalkerShreyash** [JiteshGaikwad/Chatbot-Widget#27]
I am experiencing extended response times from my chatbot in the frontend. While the backend is functioning correctly and retrieving data from the backend takes approximately 3 seconds, I am interested in finding ways to reduce the response time specifically within the frontend. I would appreciate your guidance on possible solutions to address this matter.

Thank you.

**Comment by JiteshGaikwad** [comment]
You can set the time in milliseconds 

https://github.com/JiteshGaikwad/Chatbot-Widget/blob/8afb80bfdf4da4bc3f1d3a320d2943c258ec3eb6/static/js/components/chat.js#LL42C2-L42C2

**Comment by WalkerShreyash** [comment]
Thanks @JiteshGaikwad, It helps me hence closing this issue.
