### ISSUE TITLE
Use the Widget in Wordpress

### ISSUE THREAD

**Issue by gurtajs4** [JiteshGaikwad/Chatbot-Widget#3]
Hi @JiteshGaikwad 

First of all, thanks for such beautiful widget.
I am able to get https://github.com/JiteshGaikwad/Rasa_CustomUI-v_2.0 working with Rasa Core but [this ](https://github.com/JiteshGaikwad/Chatbot-Widget) is not  running at all.

Can you please help me with that. 
Another big request would be if you can guide me using this with Wordpress Website
Can we convert this code to Plugin?

Thanks/Gurtaj

**Comment by JiteshGaikwad** [comment]
Whats the issue?

**Comment by gurtajs4** [comment]
First I am using a public server to run rasa core and Apache web-server
so i change the 
https://github.com/JiteshGaikwad/Chatbot-Widget/blob/master/static/js/script.js#L43 
as
url: `http://PUBLIC_IP:5005/conversations/${user_id}/execute`,

For rasa core i am using the project from 
https://github.com/JustinaPetr/Weatherbot_Tutorial 

#Start Custom server
python -m rasa_sdk --actions actions
#start rasa core
rasa run -m models --enable-api --cors "*" --debug

But i get below error

![image](https://user-images.githubusercontent.com/16404733/71723481-cc6b4700-2e52-11ea-8373-6bc3cb9ec431.png)


But if i use https://github.com/JiteshGaikwad/Rasa_CustomUI-v_2.0  then, it works fine

**Comment by gurtajs4** [comment]
Hi, 

Sorry I get that working, I have missed replacing localhost at multiple places.

@JiteshGaikwad I come from embedded background and really not a web guy.

can you please please help me in understand why i am not able to use https://github.com/botfront/rasa-webchat with the current rasa core project https://github.com/JustinaPetr/Weatherbot_Tutorial.

I think we somehow need to enable socket.io hook ? Please correct me.
Another very important question would be how can i use and extent this code with Wordpress as Plugin or just a widget

**Comment by JiteshGaikwad** [comment]
Hey @gurtajs4, you need to add the reference for the socket.io channel in your credentials.yml file to make it work and I haven't used WordPress yet so I don't have any idea of that.
https://rasa.com/docs/rasa/user-guide/connectors/your-own-website/#websocket-channel

**Comment by gurtajs4** [comment]
Thanks @JiteshGaikwad  I think there are more issue beside just enabling the socket.io.
The rasa version I am using is 1.0.3 but the webchat widget doesn't seems to work. Will upgrade and check and let you know.

**Comment by JiteshGaikwad** [comment]
Ok you can raise the issue in their respective repository for the same as my widget works kn rest channel. :sweat_smile: 

Closing the issue since it's not related to my widget :smile:

**Comment by rmiaouh** [comment]
@gurtajs4 Did you found a solution with the channel ?

**Comment by gurtajs4** [comment]
Yes,  you need to write a plugin

**Comment by rmiaouh** [comment]
@gurtajs4 Can you tell me more about your plugin ? if you have a tutorial ? or something else ?

**Comment by rmiaouh** [comment]
@gurtajs4 I got this issue : https://prnt.sc/qtf65k
when i use the command : rasa run -m models --enable-api --cors "*" --debug

So i tried like you to change in https://github.com/JiteshGaikwad/Chatbot-Widget/blob/master/static/js/script.js#L43
as
url: http://MY_PUBLIC_URL:5005/conversations/${user_id}/execute,
(two times)

But nothing change, do you know what i do wrong ?

Ty for your help

**Comment by gurtajs4** [comment]
Sorry for late reply, I am not sure why you are getting some memory segmentation issue.... Are you able to run moodbot?
Please PM me *gurtajs4@gmail.com*
