### ISSUE TITLE
Getting cors error on browser side while running rasa chatbot on remote server

### ISSUE THREAD

**Issue by Prskriti** [JiteshGaikwad/Chatbot-Widget#4]
<img width="1439" alt="CORS error" src="https://user-images.githubusercontent.com/26160349/74741639-32851f80-5283-11ea-912e-9fabc315acaa.png">

Any suggestions on how to fix this issue

**Comment by JiteshGaikwad** [comment]
Hey @Prskriti, try running the Rasa server using below command:

rasa run -m models --enable-api --cors "*" --debug

**Comment by Prskriti** [comment]
I tried running using  above mentioned command but issue still persist

**Comment by Prskriti** [comment]
Issue has been fixed thanks for your help.
