### ISSUE TITLE
Custom Paylod Error

### ISSUE THREAD

**Issue by athenasaurav** [JiteshGaikwad/Chatbot-Widget#5]
Hi Jitesh. 

I m using your chatbot widget https://github.com/JiteshGaikwad/Chatbot-Widget. Bot is properly responding locally. 

My issue i m facing is with the custom payload using actions.py. I want to display a card using json but the bot is just showing the json output but not card. 

My defined class is as follows :

class Location(Action):
 def name(self):
  """name of the custom action"""
  return "action_Location"

 def run(self,dispatcher,tracker,domain):	
  gt = {
            "attachment": {
                "type": "template",
                "payload": {
                    "template_type": "generic",
                    "elements": [
                                                {
                            "title": "Marine Drive",
                            "image_url":"https://www.trawell.in/admin/images/upload/486072642MarineDrive_Main.jpg",
                            "subtitle": "Marine Drive is a buzzing waterfront district known for the Marine Walkway, popular for evening strolls,..",
                            "buttons": [
                                {
                                    "type": "postback",
                                    "payload": "/marine_drive",
                                    "title": "Read More"
                                },
                              {
                                    "type": "web_url",
                                    "url": "https://www.google.com/maps/d/viewer?ie=UTF8&source=embed&oe=UTF8&msa=0&mid=1TQ2nVI6cF8LtWZxKIdXSkIJs5JI&ll=49.21193400000003%2C-123.10863&z=17",
                                    "title": "Location"
                                },  
                            ]
                        },
                        {
                            "title": "Mattancherry",
                            "image_url":"https://th.thgim.com/migration_catalog/article11297834.ece/alternates/FREE_660/MATTANCHERRY_PALACE",
                            "subtitle": "Historic Mattancherry is known for 16th-century Mattancherry Palace, built by the Portuguese in traditional Keralan style",
                            "buttons": [
                                {
                                    "type": "postback",
                                    "payload": "/mattancherry",
                                    "title": "Read More"
                                },
                                {
                                    "type": "web_url",
                                    "url": "https://www.google.com/maps/place/Mattancherry,+Kochi,+Kerala/@9.9601158,76.2455098,15z/data=!3m1!4b1!4m5!3m4!1s0x3b086d4f2efb0045:0xbfbce1be3e2c1399!8m2!3d9.9578326!4d76.2555324",
                                    "title": "Location"
                                },
                            ]
                        },
                        {
                            "title": "Fort Kochi",
                            "image_url":"https://monicasuricom.files.wordpress.com/2017/02/shutterstock_104171108.jpg",
                            "subtitle": "A charming seaside area, Fort Kochi is known for its Dutch, Portuguese, and British colonial architecture",
                            "buttons": [
                                {
                                    "type": "postback",
                                    "payload": "/fort_kochi",
                                    "title": "Read More"
                                },
                                {
                                    "type": "web_url",
                                    "url": "https://www.google.com/maps/place/Fort+Kochi,+Kochi,+Kerala/@9.9624501,76.2337644,16z/data=!4m5!3m4!1s0x3b086d314f0b178d:0xc545233f390db43b!8m2!3d9.9657787!4d76.2421147",
                                    "title": "Location"
                                }, 
                            ]
                        },
                        
                    ]
                }
            }
        }
  dispatcher.utter_message(json.dumps(gt))
  return []

and following is the output shown in the chat widget window.

![error 2](https://user-images.githubusercontent.com/530190/75109730-40a0ba80-564c-11ea-8921-74b142501976.jpg)
![error 1](https://user-images.githubusercontent.com/530190/75109731-426a7e00-564c-11ea-95c3-2be30279c793.jpg)

Also the bot was properly responding earlier:

![error 3](https://user-images.githubusercontent.com/530190/75109738-59a96b80-564c-11ea-8cda-6afe379aff0b.jpg)
![error 4](https://user-images.githubusercontent.com/530190/75109739-5b732f00-564c-11ea-9ecb-805569d5d1da.jpg)

**Comment by JiteshGaikwad** [comment]
Hey @athenasaurav, try to send the json response using the below line:

> dispatcher.utter_message(json=json.dumps(gt))
