### ISSUE TITLE
Setting Slots from Dropdown in RASA 

### ISSUE THREAD

**Issue by olahsymbo100** [JiteshGaikwad/Chatbot-Widget#7]
I need assistance with setting slots from dropdown options in RASA. Currently I'm using the dropdown from this Chatbot Widget 

However when i select the options from the webchat the slot is always set to None.

I have created slot in domain.yml, 

```
slots:
  game_name:
    type: any

entities:
- game_name

```
and also created an intent 

```
- intent: game_option
  examples: |
    - [Access Platc](game_name)
    - [Citk Platc](game_name)
    - [Diamond Platc](game_name)
```

and in stories.yml, I set this:

```
- intent: game_option
  - slot_was_set:
      - game_name
```

I dont understand why it's still returning `None`

My response is from custom actions and looks like this:

```
class ActionListGames(Action):
    def name(self) -> Text:
        return "action_list_games"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        response_games = requests.get("https://www.gamexn.com/api/v2/games")
        processed_output = json.load(io.BytesIO(response_games.content))['data']['games']

        games = [
            {
                "label": row['gameName'],
                "value": "/game_option{\"game_name\": \"" + row['gameCode'] + "\"}"
            } for row in processed_output
        ]
        message = {"payload": "dropDown", "data": games}

        dispatcher.utter_message(text="Please select a game option:", json_message=message)
        return []
```

I dont know why its still returning `None`.

**Comment by janaeshkrish** [comment]
Facing the same issue..

I am not able to save slot values on button click on dropdown

**Comment by janaeshkrish** [comment]
@JiteshGaikwad I have solved this issue how do i contribute to this project?

**Comment by KalimAmzad** [comment]
@janaeshkrish Could you please share your solution here?

**Comment by janaeshkrish** [comment]
Copy paste the code snippet in [dropDown.js](https://github.com/janaeshkrish/Chatbot-Widget/blob/main/static/js/components/dropDown.js) 
@KalimAmzad You need to send the value in a single string **value: "/inform{slot_nam':option3}"**  inorder to take effect

**Comment by KalimAmzad** [comment]
Thanks @janaeshkrish for your response. 
Do you refer single string value: "/inform{slot_nam':option3}"  or "/inform{slot_nam:option3}"  

I'm trying following that isn't working
```python
data = []
info = ["ABC", "DEF", "GHI"]
for i in info:
    temp = {"label":i, 
            "value":f"/inform{{name: {i}}}"  # also tried "value":f"/inform{{'name': '{i}'}}"
        }
    data.append(temp)
```

**Comment by janaeshkrish** [comment]
@KalimAmzad 

Try like this

![image](https://user-images.githubusercontent.com/54946830/163919768-a9a0afb1-832b-49f6-869e-7696fb25f125.png)

And you can also check [here ](https://github.com/janaeshkrish/Chatbot-Widget)

**Comment by KalimAmzad** [comment]
Tried following. Got error


UserWarning: Failed to parse arguments in line '/latest_price{script_id: DEF}'. Failed to decode parameters as a json object. Make sure the intent is followed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)


```python
data = []
info = ["ABC", "DEF", "GHI"]
intent = "latest_price"
for i in info:
    payload = f"{{script_id: {i}}}"
    data.append(
        {
            "label":i, 
            "value":f"/{intent}{payload}",
        }
    )
```

**Comment by KalimAmzad** [comment]
@janaeshkrish  I Tried following. Got error

```bash
UserWarning: Failed to parse arguments in line '/latest_price{script_id: DEF}'. Failed to decode parameters as a json object. Make sure the intent is followed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

```python
data = []
info = ["ABC", "DEF", "GHI"]
intent = "latest_price"
for i in info:
    payload = f"{{script_id: {i}}}"
    data.append(
        {
            "label":i, 
            "value":f"/{intent}{payload}",
        }
    )
```

**Comment by janaeshkrish** [comment]
@KalimAmzad I hope you are sending the message like this to the client 

![image](https://user-images.githubusercontent.com/54946830/163938020-7dfcff38-e414-42b9-bdee-525ef221d3b9.png)

**Comment by KalimAmzad** [comment]
@janaeshkrish Yeah but still got error 
```python
message={"payload":"dropDown","data":data}
dispatcher.utter_message(text="Please tell me for which script you want to know latest  price",json_message=message)
```

**Comment by JiteshGaikwad** [comment]
@KalimAmzad Please ask this question on Rasa community forum as this issue is not related to my chatbot widget, I am closing the issue since @janaeshkrish have added a fix [here](https://github.com/janaeshkrish/Chatbot-Widget)
