### ISSUE TITLE
Payloads and Hyperlinks

### ISSUE THREAD

**Issue by vinothkumar1097** [JiteshGaikwad/Chatbot-Widget#7]
Hi Jitesh,

Thanks for the awesome UI kit.
I have few doubts on how to configure payloads for below categories in domain.yml file
- Buttons
- Images
- Quick Replies
- Cards Carousels
- Dropdown
Is there any documentation available for above payloads ?

Next, how can i display text along with some hyperlinks in response ?
I tried to do like ( - text: Here is the [link] (https://xxx.yyy.net)) , but its not working as expected.

Thanks,
Vinod L

**Comment by JiteshGaikwad** [comment]
Hey @vinothkumar1097 , thanks. I don't have any documentation for the above query and the response which you are trying to send is in markdown format which my UI doesn't supports.

**Comment by vinothkumar1097** [comment]
Thanks Jitesh for the prompt reply.
So i need custom payloads for Buttons, Images, Quick replies and for dropdown. Could you please help on this.
Also for displaying hyperlinks in responses, how can i achieve it.

**Comment by JiteshGaikwad** [comment]
Hey @vinothkumar1097 , I will be writting a Blog on how to use all those elements, just wait for few days.

**Comment by vinothkumar1097** [comment]
Thanks Jitesh. It will be useful for others too.
But for displaying the hyperlinks in responses, is there any way to achieve it ?

**Comment by JiteshGaikwad** [comment]
Hey @vinothkumar1097 , can't you send the link message as it is from rasa?

**Comment by vinothkumar1097** [comment]
Sorry Jitesh for being late to reply. As my hyperlinks contain more than 200 words, it would be not user friendly to display the direct hyperlink response from rasa.
So it would be good if i encode hyperlink in a word (link). So when users click on the word link they would be redirected to the correct hyperlink.
